-- LinkNMS v2 — to-be schema (one schema per module, no cross-schema FKs).
-- Source of truth for the model: cowork/documentation/to-be/15-data-model.md
-- Conventions: ids are UUIDv7 generated by the client/app; money = bigint cents (EUR);
-- quantities = numeric(14,3); schedule dates = date; enums = text + CHECK.

CREATE SCHEMA IF NOT EXISTS platform;
CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS directory;
CREATE SCHEMA IF NOT EXISTS project;
CREATE SCHEMA IF NOT EXISTS tendering;
CREATE SCHEMA IF NOT EXISTS contracting;
CREATE SCHEMA IF NOT EXISTS planning;
CREATE SCHEMA IF NOT EXISTS quality;
CREATE SCHEMA IF NOT EXISTS documents;
CREATE SCHEMA IF NOT EXISTS collaboration;
CREATE SCHEMA IF NOT EXISTS reputation;
CREATE SCHEMA IF NOT EXISTS billing;
CREATE SCHEMA IF NOT EXISTS record;

-- ───────────────────────── platform ─────────────────────────
CREATE TABLE platform.outbox (
  event_id      uuid PRIMARY KEY,
  type          text NOT NULL,
  version       int  NOT NULL DEFAULT 1,
  occurred_at   timestamptz NOT NULL DEFAULT now(),
  project_id    uuid,
  actor         jsonb NOT NULL,
  scope         jsonb NOT NULL,
  data          jsonb NOT NULL,
  dispatched_at timestamptz
);
CREATE INDEX outbox_pending ON platform.outbox (occurred_at) WHERE dispatched_at IS NULL;

CREATE TABLE platform.holiday (
  date  date NOT NULL,
  scope text NOT NULL,               -- 'national' | municipality code (INE)
  name  text NOT NULL,
  PRIMARY KEY (date, scope)
);

-- ───────────────────────── identity (Clerk mirror — never decides a permission) ─────────────────────────
CREATE TABLE identity.person (
  id            uuid PRIMARY KEY,
  clerk_user_id text NOT NULL UNIQUE,
  email         text NOT NULL UNIQUE CHECK (email = lower(email)),
  name          text NOT NULL,
  phone         text,
  locale        text NOT NULL DEFAULT 'pt-PT' CHECK (locale IN ('pt-PT','en','es')),
  platform_role text CHECK (platform_role IN ('support','admin')),
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE identity.organization (
  id              uuid PRIMARY KEY,
  clerk_org_id    text NOT NULL UNIQUE,
  kind            text NOT NULL CHECK (kind IN ('household','contractor','consultant','supplier')),
  legal_name      text NOT NULL,
  nif             text UNIQUE,
  approval_policy text NOT NULL DEFAULT 'any' CHECK (approval_policy IN ('any','all')),
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE identity.org_membership (
  org_id     uuid NOT NULL REFERENCES identity.organization(id),
  person_id  uuid NOT NULL REFERENCES identity.person(id),
  org_role   text NOT NULL CHECK (org_role IN ('admin','manager','representative','site_lead','finance','member','inspector')),
  status     text NOT NULL DEFAULT 'active' CHECK (status IN ('active','removed')),
  synced_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (org_id, person_id)
);

CREATE TABLE identity.project_staffing (
  project_id uuid NOT NULL,
  org_id     uuid NOT NULL REFERENCES identity.organization(id),
  person_id  uuid NOT NULL REFERENCES identity.person(id),
  staffed_by uuid NOT NULL REFERENCES identity.person(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, org_id, person_id)
);

-- ───────────────────────── directory ─────────────────────────
CREATE TABLE directory.specialty (
  code        text PRIMARY KEY,
  name_pt     text NOT NULL,
  name_en     text NOT NULL,
  parent_code text REFERENCES directory.specialty(code)
);

CREATE TABLE directory.organization_profile (
  org_id                uuid PRIMARY KEY,
  display_name          text NOT NULL,
  description           text,
  logo_document_id      uuid,
  specialties           text[] NOT NULL DEFAULT '{}',
  tags                  text[] NOT NULL DEFAULT '{}',
  service_areas         text[] NOT NULL DEFAULT '{}',
  team_size_band        text CHECK (team_size_band IN ('1','2-5','6-20','21-50','50+')),
  founded_year          smallint,
  declared_nif          text,
  declared_impic_number text,
  declared_impic_class  text,
  declared_insurance    text,
  listed                boolean NOT NULL DEFAULT false,
  completeness          smallint NOT NULL DEFAULT 0 CHECK (completeness BETWEEN 0 AND 100),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE directory.portfolio_entry (
  id                 uuid PRIMARY KEY,
  org_id             uuid NOT NULL,
  source             text NOT NULL CHECK (source IN ('platform','declared')),
  contract_id        uuid,
  title              text NOT NULL,
  municipality_code  text,
  typology           text,
  specialties        text[] NOT NULL DEFAULT '{}',
  start_date         date,
  end_date           date,
  variance_wd        int,
  photo_document_ids uuid[] NOT NULL DEFAULT '{}',
  owner_consent      boolean NOT NULL DEFAULT false,
  CHECK (source = 'declared' OR contract_id IS NOT NULL)
);

-- ───────────────────────── project ─────────────────────────
CREATE TABLE project.project (
  id                      uuid PRIMARY KEY,
  owner_org_id            uuid,
  created_by_org_id       uuid NOT NULL,
  name                    text NOT NULL CHECK (length(btrim(name)) > 0),
  address                 text,
  municipality_code       text NOT NULL,
  typology                text,
  gross_area_m2           numeric(10,2),
  indicative_budget_cents bigint CHECK (indicative_budget_cents >= 0),
  status                  text NOT NULL DEFAULT 'draft'
                          CHECK (status IN ('draft','tendering','contracted','in_execution','closed','cancelled')),
  created_at              timestamptz NOT NULL DEFAULT now(),
  version                 int NOT NULL DEFAULT 1,
  CHECK (owner_org_id IS NOT NULL OR status = 'draft')
);

CREATE TABLE project.location (
  id         uuid PRIMARY KEY,
  project_id uuid NOT NULL REFERENCES project.project(id),
  parent_id  uuid REFERENCES project.location(id),
  kind       text NOT NULL CHECK (kind IN ('site','building','unit','floor','zone')),
  name       text NOT NULL,
  position   text NOT NULL
);

CREATE TABLE project.participation (
  project_id  uuid NOT NULL REFERENCES project.project(id),
  org_id      uuid NOT NULL,
  capacity    text NOT NULL CHECK (capacity IN ('owner','prime_contractor','direct_contractor','subcontractor','consultant')),
  source      text NOT NULL CHECK (source IN ('project','contract','invitation')),
  contract_id uuid,
  invite_capacity text CHECK (invite_capacity IN ('design','inspection','safety','other')),
  status      text NOT NULL DEFAULT 'active' CHECK (status IN ('active','ended')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, org_id, capacity),
  CHECK ((source = 'contract') = (contract_id IS NOT NULL))
);

CREATE TABLE project.project_invitation (
  id           uuid PRIMARY KEY,
  project_id   uuid NOT NULL REFERENCES project.project(id),
  invited_by_org_id uuid NOT NULL,
  email        text NOT NULL,
  org_id       uuid,
  capacity     text NOT NULL CHECK (capacity IN ('design','inspection','safety','other')),
  token_hash   text NOT NULL UNIQUE CHECK (char_length(token_hash) = 64),
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','revoked','expired')),
  expires_at   timestamptz NOT NULL
);

CREATE TABLE project.calendar (
  project_id uuid PRIMARY KEY REFERENCES project.project(id),
  work_days  smallint[] NOT NULL DEFAULT '{1,2,3,4,5}',
  closures   daterange[] NOT NULL DEFAULT '{}'
);

CREATE TABLE project.share_link (
  id           uuid PRIMARY KEY,
  project_id   uuid NOT NULL REFERENCES project.project(id),
  created_by_person_id uuid NOT NULL,
  audience     text NOT NULL,                 -- e.g. 'Câmara Municipal da Maia'
  document_ids uuid[] NOT NULL DEFAULT '{}',
  task_ids     uuid[] NOT NULL DEFAULT '{}',
  token_hash   text NOT NULL UNIQUE,
  expires_at   timestamptz NOT NULL,
  revoked_at   timestamptz
);

-- ───────────────────────── contracting ─────────────────────────
CREATE TABLE contracting.contract (
  id                  uuid PRIMARY KEY,
  project_id          uuid NOT NULL,
  kind                text NOT NULL CHECK (kind IN ('prime','direct','sub','service')),
  parent_contract_id  uuid REFERENCES contracting.contract(id),
  client_org_id       uuid NOT NULL,
  supplier_org_id     uuid NOT NULL,
  reference           text NOT NULL,
  specialties         text[] NOT NULL DEFAULT '{}',
  scope_inclusions    text,
  scope_exclusions    text,
  payment_terms       text NOT NULL DEFAULT 'measurement_monthly' CHECK (payment_terms IN ('measurement_monthly','milestones','mixed')),
  retention_bp        int NOT NULL DEFAULT 500 CHECK (retention_bp BETWEEN 0 AND 10000),
  payment_days        int NOT NULL DEFAULT 30,
  contractual_start   date,
  contractual_end     date,
  revision            int NOT NULL DEFAULT 1,
  origin              text NOT NULL CHECK (origin IN ('award','direct_entry')),
  origin_proposal_id  uuid,
  status              text NOT NULL DEFAULT 'draft'
                      CHECK (status IN ('draft','signed','active','provisionally_received','closed','cancelled','terminated')),
  sponsored_by_org_id uuid,
  value_cents         bigint NOT NULL DEFAULT 0,          -- materialised Σ active boq lines
  created_at          timestamptz NOT NULL DEFAULT now(),
  version             int NOT NULL DEFAULT 1,
  CHECK (client_org_id <> supplier_org_id),
  CHECK ((kind = 'sub') = (parent_contract_id IS NOT NULL)),
  CHECK (origin <> 'award' OR origin_proposal_id IS NOT NULL)
);
CREATE UNIQUE INDEX contract_one_live_prime ON contracting.contract (project_id)
  WHERE kind = 'prime' AND status NOT IN ('draft','cancelled','terminated');

CREATE TABLE contracting.contract_signature (
  contract_id uuid NOT NULL REFERENCES contracting.contract(id),
  org_id      uuid NOT NULL,
  person_id   uuid NOT NULL,
  signed_at   timestamptz NOT NULL DEFAULT now(),
  evidence_document_id uuid,
  PRIMARY KEY (contract_id, org_id)
);

-- cost lines: the BoQ, attached to where the work is (planning.task). contract_id NULL = owner estimate.
CREATE TABLE contracting.boq_item (
  id                            uuid PRIMARY KEY,
  project_id                    uuid NOT NULL,
  contract_id                   uuid REFERENCES contracting.contract(id),
  estimate_owner_org_id         uuid,
  task_id                       uuid,
  chapter                       text,
  code                          text NOT NULL,
  description                   text NOT NULL,
  unit                          text NOT NULL,
  quantity                      numeric(14,3) NOT NULL CHECK (quantity >= 0),
  unit_price_cents              bigint NOT NULL CHECK (unit_price_cents >= 0),
  material_spec                 text,
  specialty                     text,
  location_id                   uuid,
  parent_boq_item_id            uuid REFERENCES contracting.boq_item(id),
  introduced_by_change_order_id uuid,
  superseded_by_change_order_id uuid,
  CHECK ((contract_id IS NULL) = (estimate_owner_org_id IS NOT NULL))
);
CREATE UNIQUE INDEX boq_code_per_contract ON contracting.boq_item (contract_id, code) WHERE contract_id IS NOT NULL;
CREATE INDEX boq_by_task ON contracting.boq_item (task_id);

CREATE TABLE contracting.change_order (
  id                     uuid PRIMARY KEY,
  contract_id            uuid NOT NULL REFERENCES contracting.contract(id),
  number                 text NOT NULL,
  kind                   text NOT NULL CHECK (kind IN ('scope','time','scope_and_time')),
  reason                 text NOT NULL,
  amount_delta_cents     bigint NOT NULL DEFAULT 0,
  linked_change_order_id uuid REFERENCES contracting.change_order(id),
  from_variation_ids     uuid[] NOT NULL DEFAULT '{}',
  proposed_by_org_id     uuid NOT NULL,
  proposed_by_person_id  uuid NOT NULL,
  decided_by_org_id      uuid,
  decided_by_person_id   uuid,
  decided_at             timestamptz,
  decision_note          text,
  idempotency_key        text UNIQUE,
  status                 text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','submitted','approved','rejected','withdrawn')),
  created_at             timestamptz NOT NULL DEFAULT now(),
  version                int NOT NULL DEFAULT 1,
  UNIQUE (contract_id, number),
  CHECK (decided_by_org_id IS NULL OR decided_by_org_id <> proposed_by_org_id),
  CHECK ((status IN ('approved','rejected')) = (decided_by_org_id IS NOT NULL))
);

CREATE TABLE contracting.change_order_line (
  id              uuid PRIMARY KEY,
  change_order_id uuid NOT NULL REFERENCES contracting.change_order(id),
  op              text NOT NULL CHECK (op IN ('add','replace','remove')),
  boq_item_id     uuid REFERENCES contracting.boq_item(id),
  new_line        jsonb,
  CHECK (op = 'add' OR boq_item_id IS NOT NULL),
  CHECK (op = 'remove' OR new_line IS NOT NULL)
);

CREATE TABLE contracting.change_order_time (
  change_order_id     uuid NOT NULL REFERENCES contracting.change_order(id),
  task_id             uuid NOT NULL,
  new_baseline_start  date,
  new_baseline_finish date,
  PRIMARY KEY (change_order_id, task_id)
);

CREATE TABLE contracting.measurement (
  id                    uuid PRIMARY KEY,
  contract_id           uuid NOT NULL REFERENCES contracting.contract(id),
  period                text NOT NULL CHECK (period ~ '^\d{4}-\d{2}$'),
  status                text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','submitted','approved','disputed')),
  gross_cents           bigint NOT NULL DEFAULT 0,
  retention_cents       bigint NOT NULL DEFAULT 0,
  net_cents             bigint NOT NULL DEFAULT 0,
  submitted_by_person_id uuid,
  approved_by_person_id uuid,
  approved_at           timestamptz,
  UNIQUE (contract_id, period)
);

CREATE TABLE contracting.measurement_line (
  measurement_id       uuid NOT NULL REFERENCES contracting.measurement(id),
  boq_item_id          uuid NOT NULL REFERENCES contracting.boq_item(id),
  quantity_this_period numeric(14,3) NOT NULL CHECK (quantity_this_period >= 0),
  PRIMARY KEY (measurement_id, boq_item_id)
);

CREATE TABLE contracting.payment_record (
  id                     uuid PRIMARY KEY,
  contract_id            uuid NOT NULL REFERENCES contracting.contract(id),
  measurement_id         uuid REFERENCES contracting.measurement(id),
  milestone_label        text,
  amount_cents           bigint NOT NULL CHECK (amount_cents >= 0),
  due_date               date NOT NULL,
  status                 text NOT NULL DEFAULT 'expected' CHECK (status IN ('expected','declared_paid','confirmed','disputed')),
  declared_paid_at       timestamptz,
  declared_by_person_id  uuid,
  confirmed_at           timestamptz,
  confirmed_by_person_id uuid,
  CHECK (measurement_id IS NOT NULL OR milestone_label IS NOT NULL)
);

-- ───────────────────────── tendering ─────────────────────────
CREATE TABLE tendering.rfp (
  id                  uuid PRIMARY KEY,
  project_id          uuid NOT NULL,
  issuer_org_id       uuid NOT NULL,
  level               text NOT NULL CHECK (level IN ('owner','sub')),
  parent_contract_id  uuid,
  title               text NOT NULL,
  scope_text          text,
  specialties         text[] NOT NULL DEFAULT '{}',
  visibility          text NOT NULL DEFAULT 'invite_only' CHECK (visibility IN ('invite_only','open')),
  questions_deadline  timestamptz,
  submission_deadline timestamptz NOT NULL,
  package_version     int NOT NULL DEFAULT 1,
  status              text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','closed','awarded','cancelled')),
  awarded_proposal_id uuid,
  created_at          timestamptz NOT NULL DEFAULT now(),
  version             int NOT NULL DEFAULT 1,
  CHECK ((level = 'sub') = (parent_contract_id IS NOT NULL))
);

CREATE TABLE tendering.rfp_root (
  rfp_id  uuid NOT NULL REFERENCES tendering.rfp(id),
  task_id uuid NOT NULL,
  PRIMARY KEY (rfp_id, task_id)
);

CREATE TABLE tendering.rfp_package_row (
  rfp_id          uuid NOT NULL REFERENCES tendering.rfp(id),
  package_version int NOT NULL,
  task_id         uuid NOT NULL,
  parent_task_id  uuid,
  name            text NOT NULL,
  scope_text      text,
  specialty       text,
  position        text NOT NULL,
  PRIMARY KEY (rfp_id, package_version, task_id)
);

CREATE TABLE tendering.rfp_item (
  id              uuid PRIMARY KEY,
  rfp_id          uuid NOT NULL REFERENCES tendering.rfp(id),
  package_version int NOT NULL,
  task_id         uuid NOT NULL,
  code            text NOT NULL,
  description     text NOT NULL,
  unit            text NOT NULL,
  quantity        numeric(14,3) NOT NULL,
  material_spec   text,
  specialty       text
);

CREATE TABLE tendering.rfp_recipient (
  id               uuid PRIMARY KEY,
  rfp_id           uuid NOT NULL REFERENCES tendering.rfp(id),
  org_id           uuid,
  email            text NOT NULL,
  token_hash       text NOT NULL UNIQUE CHECK (char_length(token_hash) = 64),
  email_message_id text,
  status           text NOT NULL DEFAULT 'queued'
                   CHECK (status IN ('queued','sent','opened','declined','proposal_submitted','bounced')),
  sent_at          timestamptz,
  opened_at        timestamptz,
  UNIQUE (rfp_id, email)
);

CREATE TABLE tendering.rfp_addendum (
  rfp_id          uuid NOT NULL REFERENCES tendering.rfp(id),
  package_version int NOT NULL,
  summary         text NOT NULL,
  published_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (rfp_id, package_version)
);

CREATE TABLE tendering.clarification (
  id              uuid PRIMARY KEY,
  rfp_id          uuid NOT NULL REFERENCES tendering.rfp(id),
  asked_by_org_id uuid NOT NULL,          -- never exposed to other bidders
  question        text NOT NULL,
  answer          text,
  answered_at     timestamptz,
  status          text NOT NULL DEFAULT 'open' CHECK (status IN ('open','answered'))
);

-- one proposal per recipient = the lane (D-36)
CREATE TABLE tendering.proposal (
  id                    uuid PRIMARY KEY,
  rfp_id                uuid NOT NULL REFERENCES tendering.rfp(id),
  recipient_id          uuid NOT NULL UNIQUE REFERENCES tendering.rfp_recipient(id),
  bidder_org_id         uuid,
  channel               text NOT NULL DEFAULT 'platform' CHECK (channel IN ('platform','email')),
  current_revision      int NOT NULL DEFAULT 0,
  status                text NOT NULL DEFAULT 'invited'
                        CHECK (status IN ('invited','draft','submitted','withdrawn','shortlisted','awarded','declined')),
  summary_total_cents   bigint,
  summary_duration_wd   int,
  summary_start         date,
  conditions            text,
  validity_until        date,
  recorded_by_person_id uuid,
  document_ids          uuid[] NOT NULL DEFAULT '{}',
  version               int NOT NULL DEFAULT 1,
  CHECK (channel = 'platform' OR recorded_by_person_id IS NOT NULL OR status = 'invited')
);

CREATE TABLE tendering.proposal_revision (
  proposal_id  uuid NOT NULL REFERENCES tendering.proposal(id),
  revision     int NOT NULL,
  total_cents  bigint NOT NULL,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (proposal_id, revision)
);

CREATE TABLE tendering.proposal_row (
  id               uuid PRIMARY KEY,
  proposal_id      uuid NOT NULL REFERENCES tendering.proposal(id),
  packaged_task_id uuid,                   -- null = row added by the bidder
  parent_row_id    uuid REFERENCES tendering.proposal_row(id),
  kind             text NOT NULL DEFAULT 'task' CHECK (kind IN ('task','summary','milestone')),
  name             text NOT NULL,
  duration_wd      int,
  start            date,
  finish           date,
  position         text NOT NULL
);

CREATE TABLE tendering.proposal_link (
  proposal_id     uuid NOT NULL REFERENCES tendering.proposal(id),
  predecessor_row uuid NOT NULL REFERENCES tendering.proposal_row(id),
  successor_row   uuid NOT NULL REFERENCES tendering.proposal_row(id),
  from_anchor     text NOT NULL CHECK (from_anchor IN ('start','end')),
  to_anchor       text NOT NULL CHECK (to_anchor IN ('start','end')),
  lag_wd          int NOT NULL DEFAULT 0,
  PRIMARY KEY (predecessor_row, successor_row)
);

CREATE TABLE tendering.proposal_line (
  id               uuid PRIMARY KEY,
  proposal_id      uuid NOT NULL REFERENCES tendering.proposal(id),
  rfp_item_id      uuid REFERENCES tendering.rfp_item(id),
  proposal_row_id  uuid REFERENCES tendering.proposal_row(id),
  is_variant       boolean NOT NULL DEFAULT false,
  description      text NOT NULL,
  unit             text NOT NULL,
  quantity         numeric(14,3) NOT NULL,
  unit_price_cents bigint NOT NULL CHECK (unit_price_cents >= 0),
  material_spec    text,
  CHECK (is_variant OR rfp_item_id IS NOT NULL)
);

-- ───────────────────────── planning ─────────────────────────
CREATE TABLE planning.task (
  id                        uuid PRIMARY KEY,
  project_id                uuid NOT NULL,
  parent_id                 uuid REFERENCES planning.task(id),
  depth                     smallint NOT NULL CHECK (depth BETWEEN 1 AND 10),
  position                  text NOT NULL,               -- fractional index
  kind                      text NOT NULL DEFAULT 'task' CHECK (kind IN ('task','summary','milestone')),
  name                      text NOT NULL,
  description               text,
  specialty                 text,
  location_id               uuid,
  contract_id               uuid,                         -- set on the branch root when signed
  assignee_org_id           uuid,
  assignee_person_id        uuid,
  assignee_inherited        boolean NOT NULL DEFAULT true,
  dating_mode               text NOT NULL DEFAULT 'undated' CHECK (dating_mode IN ('dated','undated','external')),
  start                     date,
  finish                    date,
  duration_wd               int CHECK (duration_wd >= 0),
  actual_start              date,
  actual_finish             date,
  acceptance_criteria       text,
  -- materialised derivations (recomputed by the planning module)
  branch_contract_id        uuid,
  baseline_start            date,
  baseline_finish           date,
  schedule_state            text NOT NULL DEFAULT 'planned'
                            CHECK (schedule_state IN ('planned','on_baseline','extended','sequence_warning')),
  last_changed_by_person_id uuid,
  last_changed_by_org_id    uuid,
  last_changed_at           timestamptz,
  last_change_cause         text,
  deleted_at                timestamptz,
  CHECK (finish IS NULL OR start IS NULL OR finish >= start),
  CHECK (kind <> 'milestone' OR start IS NULL OR finish IS NULL OR start = finish),
  CHECK (dating_mode <> 'dated' OR kind = 'summary' OR start IS NOT NULL)
);
CREATE INDEX task_tree ON planning.task (project_id, parent_id, position) WHERE deleted_at IS NULL;

CREATE TABLE planning.task_field_change (
  id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  task_id             uuid NOT NULL REFERENCES planning.task(id),
  field               text NOT NULL,
  old_value           jsonb,
  new_value           jsonb,
  base_value          jsonb,
  changed_by_person_id uuid NOT NULL,
  changed_by_org_id   uuid NOT NULL,
  changed_at          timestamptz NOT NULL DEFAULT now(),
  cause               text NOT NULL CHECK (cause IN ('direct','propagated','template','import','award')),
  channel             text NOT NULL DEFAULT 'ui' CHECK (channel IN ('ui','mcp','api','import','system')),
  cause_task_id       uuid,
  client_change_id    uuid,
  UNIQUE (client_change_id, task_id, field)
);

CREATE TABLE planning.checklist_item (
  id                uuid PRIMARY KEY,
  task_id           uuid NOT NULL REFERENCES planning.task(id),
  text              text NOT NULL,
  done              boolean NOT NULL DEFAULT false,
  done_by_person_id uuid,
  done_at           timestamptz,
  position          text NOT NULL
);

CREATE TABLE planning.link (
  id                   uuid PRIMARY KEY,
  project_id           uuid NOT NULL,
  predecessor_id       uuid NOT NULL REFERENCES planning.task(id),
  successor_id         uuid NOT NULL REFERENCES planning.task(id),
  from_anchor          text NOT NULL CHECK (from_anchor IN ('start','end')),
  to_anchor            text NOT NULL CHECK (to_anchor IN ('start','end')),
  lag_wd               int NOT NULL DEFAULT 0,
  created_by_org_id    uuid NOT NULL,
  created_by_person_id uuid NOT NULL,
  UNIQUE (predecessor_id, successor_id),
  CHECK (predecessor_id <> successor_id)
);

CREATE TABLE planning.baseline (
  id             uuid PRIMARY KEY,
  project_id     uuid NOT NULL,
  contract_id    uuid NOT NULL,
  version        int NOT NULL,
  reason         text NOT NULL CHECK (reason IN ('contract_signed','change_order')),
  change_order_id uuid,
  taken_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (contract_id, version)
);

CREATE TABLE planning.baseline_root (
  baseline_id uuid NOT NULL REFERENCES planning.baseline(id),
  task_id     uuid NOT NULL,
  PRIMARY KEY (baseline_id, task_id)
);

CREATE TABLE planning.baseline_task (
  baseline_id         uuid NOT NULL REFERENCES planning.baseline(id),
  task_id             uuid NOT NULL,
  start               date,
  finish              date,
  duration_wd         int,
  name                text NOT NULL,
  scope_text          text,
  acceptance_criteria text,
  PRIMARY KEY (baseline_id, task_id)
);

CREATE TABLE planning.baseline_cost_line (
  baseline_id      uuid NOT NULL REFERENCES planning.baseline(id),
  boq_item_id      uuid NOT NULL,
  quantity         numeric(14,3) NOT NULL,
  unit_price_cents bigint NOT NULL,
  material_spec    text,
  PRIMARY KEY (baseline_id, boq_item_id)
);

CREATE TABLE planning.variation (
  id                     uuid PRIMARY KEY,
  project_id             uuid NOT NULL,
  task_id                uuid NOT NULL REFERENCES planning.task(id),
  kind                   text NOT NULL CHECK (kind IN ('time','cost','material','scope')),
  scope_type             text NOT NULL CHECK (scope_type IN ('project','contract')),
  scope_id               uuid NOT NULL,
  baseline_value         jsonb,
  current_value          jsonb,
  delta                  jsonb NOT NULL,
  cause                  text NOT NULL CHECK (cause IN ('direct','propagated')),
  cause_task_id          uuid,
  first_changed_at       timestamptz NOT NULL,
  last_changed_at        timestamptz NOT NULL,
  last_changed_by_org_id uuid NOT NULL,
  status                 text NOT NULL DEFAULT 'open' CHECK (status IN ('open','acknowledged','formalised','closed')),
  change_order_id        uuid,
  CHECK ((kind IN ('cost','material')) = (scope_type = 'contract'))
);
CREATE UNIQUE INDEX one_open_variation ON planning.variation (task_id, kind, scope_id)
  WHERE status IN ('open','acknowledged');

CREATE TABLE planning.variation_ack (
  variation_id    uuid NOT NULL REFERENCES planning.variation(id),
  org_id          uuid NOT NULL,
  person_id       uuid NOT NULL,
  acknowledged_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (variation_id, person_id, acknowledged_at)
);

CREATE TABLE planning.variation_digest (
  id                          uuid PRIMARY KEY,
  project_id                  uuid NOT NULL,
  window_start                timestamptz NOT NULL,
  window_end                  timestamptz NOT NULL,
  variation_ids               uuid[] NOT NULL,
  net_project_finish_delta_wd int NOT NULL DEFAULT 0,
  recipient_person_id         uuid NOT NULL,
  net_cost_delta_cents        bigint,           -- per recipient (visibility applied)
  sent_at                     timestamptz
);

CREATE TABLE planning.progress_report (
  task_id               uuid NOT NULL REFERENCES planning.task(id),
  seq                   int NOT NULL,
  status                text NOT NULL CHECK (status IN ('not_started','in_progress','blocked','done','verified')),
  percent               smallint CHECK (percent BETWEEN 0 AND 100),
  note                  text,
  photo_document_ids    uuid[] NOT NULL DEFAULT '{}',
  reported_by_org_id    uuid NOT NULL,
  reported_by_person_id uuid NOT NULL,
  on_behalf_of_org_id   uuid,                  -- proxy reporting (client reports for a sub)
  reported_at           timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (task_id, seq),
  CHECK (percent IS NULL OR status = 'in_progress')
);

CREATE TABLE planning.plan_template (
  id                   uuid PRIMARY KEY,
  scope                text NOT NULL CHECK (scope IN ('personal','org','public','library')),
  owner_person_id      uuid,
  owner_org_id         uuid,
  name                 text NOT NULL,
  description          text,
  construction_type    text NOT NULL,
  phase_tags           text[] NOT NULL DEFAULT '{}',
  created_from_task_id uuid,
  uses_count           int NOT NULL DEFAULT 0,
  CHECK (scope = 'library' OR owner_person_id IS NOT NULL OR owner_org_id IS NOT NULL)
);

CREATE TABLE planning.plan_template_row (
  template_id    uuid NOT NULL REFERENCES planning.plan_template(id),
  row_key        text NOT NULL,
  parent_row_key text,
  position       text NOT NULL,
  kind           text NOT NULL CHECK (kind IN ('task','summary','milestone')),
  name           text NOT NULL,
  specialty      text,
  PRIMARY KEY (template_id, row_key)
);

CREATE TABLE planning.plan_template_link (
  template_id  uuid NOT NULL REFERENCES planning.plan_template(id),
  from_row_key text NOT NULL,
  to_row_key   text NOT NULL,
  from_anchor  text NOT NULL CHECK (from_anchor IN ('start','end')),
  to_anchor    text NOT NULL CHECK (to_anchor IN ('start','end')),
  lag_wd       int NOT NULL DEFAULT 0,
  PRIMARY KEY (template_id, from_row_key, to_row_key)
);

CREATE TABLE planning.schedule_import (
  id                   uuid PRIMARY KEY,
  project_id           uuid NOT NULL,
  target_parent_id     uuid,
  filename             text NOT NULL,
  sheet_name           text,
  column_mapping       jsonb,
  status               text NOT NULL DEFAULT 'uploaded' CHECK (status IN ('uploaded','mapped','previewed','confirmed','failed')),
  imported_by_person_id uuid NOT NULL,
  created_at           timestamptz NOT NULL DEFAULT now()
);

-- ───────────────────────── quality ─────────────────────────
CREATE TABLE quality.verification_request (
  id                   uuid PRIMARY KEY,
  task_id              uuid NOT NULL,
  requested_by_org_id  uuid NOT NULL,
  criteria_snapshot    text,
  status               text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected')),
  decided_by_org_id    uuid,
  decided_by_person_id uuid,
  reason               text,
  decided_at           timestamptz,
  CHECK (decided_by_org_id IS NULL OR decided_by_org_id <> requested_by_org_id),
  CHECK (status <> 'rejected' OR reason IS NOT NULL)
);

CREATE TABLE quality.nonconformity (
  id                 uuid PRIMARY KEY,
  project_id         uuid NOT NULL,
  task_id            uuid,
  contract_id        uuid,
  kind               text NOT NULL DEFAULT 'quality' CHECK (kind IN ('quality','safety')),
  raised_by_org_id   uuid NOT NULL,
  raised_by_person_id uuid NOT NULL,
  assigned_to_org_id uuid,
  severity           text NOT NULL CHECK (severity IN ('minor','major','critical')),
  description        text NOT NULL,
  photo_document_ids uuid[] NOT NULL DEFAULT '{}',
  status             text NOT NULL DEFAULT 'open' CHECK (status IN ('open','assigned','fixed','closed','rejected_fix')),
  closed_by_org_id   uuid,
  CHECK (closed_by_org_id IS NULL OR closed_by_org_id = raised_by_org_id)
);

CREATE TABLE quality.inspection (
  id               uuid PRIMARY KEY,
  project_id       uuid NOT NULL,
  inspector_org_id uuid NOT NULL,
  kind             text NOT NULL DEFAULT 'quality' CHECK (kind IN ('quality','safety')),
  date             date NOT NULL,
  checklist        jsonb NOT NULL DEFAULT '[]',
  findings         text,
  task_ids         uuid[] NOT NULL DEFAULT '{}'
);

-- ───────────────────────── documents ─────────────────────────
CREATE TABLE documents.document (
  id                   uuid PRIMARY KEY,
  project_id           uuid,
  scope_type           text NOT NULL CHECK (scope_type IN ('project','location','contract','task','rfp','proposal','profile','change_order','measurement','nonconformity')),
  scope_id             uuid NOT NULL,
  kind                 text NOT NULL CHECK (kind IN ('drawing','bim','photo','spec','contract_doc','invoice','other')),
  title                text NOT NULL,
  share_with_ancestors boolean NOT NULL DEFAULT false,
  current_version      int NOT NULL DEFAULT 0
);

CREATE TABLE documents.document_version (
  document_id           uuid NOT NULL REFERENCES documents.document(id),
  version_no            int NOT NULL,
  storage_key           text NOT NULL,
  mime                  text NOT NULL,
  size_bytes            bigint NOT NULL CHECK (size_bytes > 0),
  sha256                text NOT NULL CHECK (char_length(sha256) = 64),
  uploaded_by_person_id uuid NOT NULL,
  uploaded_by_org_id    uuid NOT NULL,
  uploaded_at           timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (document_id, version_no)
);

-- ───────────────────────── collaboration ─────────────────────────
CREATE TABLE collaboration.thread (
  id          uuid PRIMARY KEY,
  project_id  uuid,
  object_type text NOT NULL,
  object_id   uuid NOT NULL,
  UNIQUE (object_type, object_id)
);

CREATE TABLE collaboration.comment (
  id                 uuid PRIMARY KEY,
  thread_id          uuid NOT NULL REFERENCES collaboration.thread(id),
  author_person_id   uuid NOT NULL,
  author_org_id      uuid NOT NULL,
  kind               text NOT NULL DEFAULT 'note' CHECK (kind IN ('note','question','answer')),
  body               text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 8000),
  mentions           uuid[] NOT NULL DEFAULT '{}',
  addressee_org_id   uuid,
  question_status    text CHECK (question_status IN ('open','answered','resolved')),
  answers_comment_id uuid REFERENCES collaboration.comment(id),
  created_at         timestamptz NOT NULL DEFAULT now(),
  editable_until     timestamptz NOT NULL DEFAULT now() + interval '10 minutes',
  deleted_at         timestamptz,
  CHECK ((kind = 'question') = (question_status IS NOT NULL)),
  CHECK (kind <> 'answer' OR answers_comment_id IS NOT NULL)
);

CREATE TABLE collaboration.meeting_minute (
  id         uuid PRIMARY KEY,
  project_id uuid NOT NULL,
  date       date NOT NULL,
  attendees  uuid[] NOT NULL,
  status     text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','circulated','acknowledged'))
);
CREATE TABLE collaboration.minute_item (
  id          uuid PRIMARY KEY,
  minute_id   uuid NOT NULL REFERENCES collaboration.meeting_minute(id),
  text        text NOT NULL,
  owner_org_id uuid,
  due_date    date,
  object_type text,
  object_id   uuid
);
CREATE TABLE collaboration.minute_ack (
  minute_id uuid NOT NULL REFERENCES collaboration.meeting_minute(id),
  org_id    uuid NOT NULL,
  person_id uuid NOT NULL,
  at        timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (minute_id, org_id)
);

CREATE TABLE collaboration.notification (
  id         uuid PRIMARY KEY,
  person_id  uuid NOT NULL,
  event_id   uuid,
  category   text NOT NULL,
  title      text NOT NULL,
  object_ref jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  read_at    timestamptz
);
CREATE TABLE collaboration.notification_preference (
  person_id uuid NOT NULL,
  category  text NOT NULL,
  channel   text NOT NULL CHECK (channel IN ('in_app','email')),
  enabled   boolean NOT NULL DEFAULT true,
  PRIMARY KEY (person_id, category, channel)
);
CREATE TABLE collaboration.variation_subscription (
  project_id uuid NOT NULL,
  org_id     uuid NOT NULL,
  kinds      text[] NOT NULL,                  -- e.g. architect: {scope,material}
  PRIMARY KEY (project_id, org_id)
);

-- ───────────────────────── reputation ─────────────────────────
CREATE TABLE reputation.review (
  id                   uuid PRIMARY KEY,
  reviewer_org_id      uuid NOT NULL,
  subject_org_id       uuid NOT NULL,
  anchor_type          text NOT NULL CHECK (anchor_type IN ('contract','subcontract_work')),
  anchor_id            uuid NOT NULL,
  rating_quality       smallint NOT NULL CHECK (rating_quality BETWEEN 1 AND 5),
  rating_schedule      smallint NOT NULL CHECK (rating_schedule BETWEEN 1 AND 5),
  rating_communication smallint NOT NULL CHECK (rating_communication BETWEEN 1 AND 5),
  rating_payment       smallint CHECK (rating_payment BETWEEN 1 AND 5),
  body                 text,
  status               text NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted','published')),
  published_at         timestamptz,
  reply_body           text,
  replied_at           timestamptz,
  UNIQUE (reviewer_org_id, subject_org_id, anchor_type, anchor_id),
  CHECK (reviewer_org_id <> subject_org_id)
);
CREATE TABLE reputation.performance_snapshot (
  org_id              uuid NOT NULL,
  computed_on         date NOT NULL,
  on_time_rate        numeric(5,4),
  first_pass_rate     numeric(5,4),
  cos_per_contract    numeric(6,2),
  median_answer_hours numeric(8,2),
  contracts_completed int NOT NULL DEFAULT 0,
  PRIMARY KEY (org_id, computed_on)
);

-- ───────────────────────── billing ─────────────────────────
CREATE TABLE billing.plan (
  code         text PRIMARY KEY,
  org_kind     text NOT NULL CHECK (org_kind IN ('household','contractor','consultant','supplier')),
  name         text NOT NULL,
  price_cents  bigint NOT NULL,
  interval     text NOT NULL CHECK (interval IN ('month','year','project')),
  entitlements jsonb NOT NULL
);
CREATE TABLE billing.subscription (
  id                 uuid PRIMARY KEY,
  org_id             uuid NOT NULL UNIQUE,
  plan_code          text NOT NULL REFERENCES billing.plan(code),
  status             text NOT NULL CHECK (status IN ('trialing','active','past_due','canceled')),
  current_period_end timestamptz,
  provider_ref       text
);
CREATE TABLE billing.sponsorship (
  contract_id      uuid PRIMARY KEY,
  sponsor_org_id   uuid NOT NULL,
  sponsored_org_id uuid NOT NULL,
  starts_at        timestamptz NOT NULL DEFAULT now(),
  ends_at          timestamptz,
  CHECK (sponsor_org_id <> sponsored_org_id)
);
CREATE TABLE billing.add_on (
  id       uuid PRIMARY KEY,
  org_id   uuid NOT NULL,
  kind     text NOT NULL CHECK (kind IN ('open_rfp_credits','promotion')),
  quantity int NOT NULL,
  period   text NOT NULL
);

-- ───────────────────────── record (tamper-evident ledger) ─────────────────────────
CREATE TABLE record.audit_event (
  project_id      uuid NOT NULL,
  seq             bigint NOT NULL,
  occurred_at     timestamptz NOT NULL,
  actor_person_id uuid,
  actor_org_id    uuid,
  actor_org_role  text,
  channel         text NOT NULL DEFAULT 'ui' CHECK (channel IN ('ui','mcp','api','import','system')),
  category        text NOT NULL CHECK (category IN ('project','tendering','contracting','planning','quality','documents','collaboration','identity')),
  type            text NOT NULL,
  scope_type      text NOT NULL CHECK (scope_type IN ('project','contract','org_private','rfp_private')),
  scope_id        uuid NOT NULL,
  object_type     text NOT NULL,
  object_id       uuid NOT NULL,
  payload         jsonb NOT NULL,
  payload_hash    bytea NOT NULL,
  prev_hash       bytea,
  entry_hash      bytea NOT NULL,
  PRIMARY KEY (project_id, seq),
  UNIQUE (project_id, entry_hash)
);

-- sole writer: per-project advisory lock, monotonic seq, hash chain
CREATE OR REPLACE FUNCTION record.append_event(
  p_project uuid, p_occurred timestamptz, p_person uuid, p_org uuid, p_role text,
  p_category text, p_type text, p_scope_type text, p_scope_id uuid,
  p_object_type text, p_object_id uuid, p_payload jsonb, p_channel text DEFAULT 'ui')
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_seq bigint; v_prev bytea; v_ph bytea; v_entry bytea;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(p_project::text, 0));
  SELECT seq, entry_hash INTO v_seq, v_prev FROM record.audit_event
   WHERE project_id = p_project ORDER BY seq DESC LIMIT 1;
  v_seq := coalesce(v_seq, 0) + 1;
  v_ph := sha256(convert_to(p_payload::text, 'UTF8'));
  v_entry := sha256(coalesce(v_prev, ''::bytea) || v_ph
                    || convert_to(v_seq::text || '|' || p_occurred::text || '|' || p_scope_type || ':' || p_scope_id::text, 'UTF8'));
  INSERT INTO record.audit_event VALUES
    (p_project, v_seq, p_occurred, p_person, p_org, p_role, p_channel, p_category, p_type,
     p_scope_type, p_scope_id, p_object_type, p_object_id, p_payload, v_ph, v_prev, v_entry);
  RETURN v_seq;
END $$;

-- append-only guards
CREATE OR REPLACE FUNCTION record.forbid_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME; END $$;
CREATE TRIGGER audit_event_append_only BEFORE UPDATE OR DELETE ON record.audit_event
  FOR EACH ROW EXECUTE FUNCTION record.forbid_mutation();
CREATE TRIGGER progress_append_only BEFORE UPDATE OR DELETE ON planning.progress_report
  FOR EACH ROW EXECUTE FUNCTION record.forbid_mutation();
CREATE TRIGGER field_change_append_only BEFORE UPDATE OR DELETE ON planning.task_field_change
  FOR EACH ROW EXECUTE FUNCTION record.forbid_mutation();
CREATE TRIGGER baseline_task_append_only BEFORE UPDATE OR DELETE ON planning.baseline_task
  FOR EACH ROW EXECUTE FUNCTION record.forbid_mutation();
CREATE TRIGGER document_version_append_only BEFORE UPDATE OR DELETE ON documents.document_version
  FOR EACH ROW EXECUTE FUNCTION record.forbid_mutation();

-- post-signature BoQ lines never change in place (C4): only supersession columns may be set
CREATE OR REPLACE FUNCTION contracting.boq_freeze_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_status text;
BEGIN
  IF OLD.contract_id IS NULL THEN RETURN NEW; END IF;
  SELECT status INTO v_status FROM contracting.contract WHERE id = OLD.contract_id;
  IF v_status IN ('draft','cancelled') THEN RETURN NEW; END IF;
  IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'boq_item of a signed contract cannot be deleted'; END IF;
  IF (NEW.quantity, NEW.unit_price_cents, NEW.description, NEW.code) IS DISTINCT FROM
     (OLD.quantity, OLD.unit_price_cents, OLD.description, OLD.code) THEN
    RAISE EXCEPTION 'boq_item of a signed contract changes only via change order (supersede + add)';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER boq_freeze BEFORE UPDATE OR DELETE ON contracting.boq_item
  FOR EACH ROW EXECUTE FUNCTION contracting.boq_freeze_guard();
